package lab6;
import cse131.ArgsProcessor;
/**
 * 
 * @author seanmcmanus
 *
 */

public class Beer {
	/**
	 * This method generates a string of the song "n bottles of beer on the wall"
	 * @param how many rounds of the song are sung
	 * @return string of "bottles of beer song"
	 */
	public static String beer(int n){
		String song = "";
		if(n == 0){
			return ""; //ends song when no beer is left
		}
		else{
			song = "" + n + " bottles of beer on the wall, " + n + " bottles of beer; you take one down, pass it around, " + (n - 1) + " bottles of beer on the wall. \n" + beer(n-1);
		}
		return song;
	}
	/**
	 * Main method
	 * @param intakes how many rounds of the song is sung
	 * prints the string generated by the reucrsive loop
	 */
	public static void main(String[] args) {
		ArgsProcessor ap = new ArgsProcessor(args);
		int rounds = ap.nextInt("How many bottles of beer on the wall?");
		System.out.println(beer(rounds));

	}

}
